exports.mono = [
"./image_m/back1.png", "./image_m/meguriL3bottom.png", 
"./image_m/back2.png", "./image_m/meguriR1bottom.png", 
"./image_m/back3.png", "./image_m/meguriR2bottom.png", 
"./image_m/bottom1.png", "./image_m/meguriR3bottom.png", 
"./image_m/deko1face.png", "./image_m/nade1face.png", 
"./image_m/deko2back1.png", "./image_m/nade2face.png", 
"./image_m/deko2back2.png", "./image_m/nade3face.png", 
"./image_m/deko2back3.png", "./image_m/pero1top1.png", 
"./image_m/deko2face.png", "./image_m/pero1top2.png", 
"./image_m/deko3face.png", "./image_m/pero2top1.png", 
"./image_m/face1.png", "./image_m/pero2top2.png", 
"./image_m/face2.png", "./image_m/pero3top1.png", 
"./image_m/face3.png", "./image_m/pero3top2.png", 
"./image_m/meguriE1bottom.png", "./image_m/puri1face.png", 
"./image_m/meguriE1front.png", "./image_m/puri2face.png", 
"./image_m/meguriE2bottom.png", "./image_m/puri3face.png", 
"./image_m/meguriE2front.png", "./image_m/top_b.png", 
"./image_m/meguriL1bottom.png", "./image_m/top_l.png", 
"./image_m/meguriL2bottom.png", 
"./imagemisc/bg.jpg", "./imagemisc/icon_h3.png", 
"./imagemisc/dekoh1.png", "./imagemisc/nadeh1.png", 
"./imagemisc/icon_candy.png", "./imagemisc/nadeh2.png", 
"./imagemisc/icon_h1.png", "./imagemisc/nadeh3.png", 
"./imagemisc/icon_h2.png", "./imagemisc/purih1.png"
];
exports.color = [
"./image/back1.png", "./image/meguriE1bottom.png", "./image/pero1top1.png", 
"./image/back2.png", "./image/meguriE1front.png", "./image/pero1top2.png", 
"./image/back3.png", "./image/meguriE2bottom.png", "./image/pero2top1.png", 
"./image/bottom1.png", "./image/meguriE2front.png", "./image/pero2top2.png", 
"./image/deko1face.png", "./image/meguriL1bottom.png", "./image/pero3top1.png", 
"./image/deko2back1.png", "./image/meguriL2bottom.png", "./image/pero3top2.png", 
"./image/deko2back2.png", "./image/meguriL3bottom.png", "./image/puri1face.png", 
"./image/deko2back3.png", "./image/meguriR1bottom.png", "./image/puri2face.png", 
"./image/deko2face.png", "./image/meguriR2bottom.png", "./image/puri3face.png", 
"./image/deko3face.png", "./image/meguriR3bottom.png", "./image/top_b.png", 
"./image/face1.png", "./image/nade1face.png", "./image/top_l.png", 
"./image/face2.png", "./image/nade2face.png", 
"./image/face3.png", "./image/nade3face.png", 
"./imagemisc/bg.jpg", "./imagemisc/icon_h3.png", 
"./imagemisc/dekoh1.png", "./imagemisc/nadeh1.png", 
"./imagemisc/icon_candy.png", "./imagemisc/nadeh2.png", 
"./imagemisc/icon_h1.png", "./imagemisc/nadeh3.png", 
"./imagemisc/icon_h2.png", "./imagemisc/purih1.png"
];
